### ISSUE TITLE
create SASAP project document

### ISSUE THREAD

**Issue by mbjones** [NCEAS/project-papers#41]
Create a project document showing the SASAP project info serialized into the emerging project description format.

**Comment by emilyodean** [comment]
Example XML for SASAP here - https://github.com/NCEAS/project-papers/blob/master/ProjectPageXML2.xml

**Comment by emilyodean** [comment]
- [ ] Decide what to do about acknowledgments (are `funding` and `acknowledgements` two unique elements, or should `funding` contain `acknowledgements`? 
- [ ] Decide if/how we should restrict length of string for `tagline` 
- [ ] Decide how to handle logos (all as `images`? or some type `logo`?)
- [ ] Solidify containers for markdown in project pages (`projectDescription`, `resultsOverview`, etc)

**Comment by emilyodean** [comment]
@mbjones and @smfreund, not sure if the meeting today is going to be used for more discussion on this, but wanted to get the ball rolling here. 

My opinions on the above - 
1) Acknowledgements should have its own slot in project separate from funding since these two things may be completely unrelated.
2) Describe and give an example of an appropriate length of tagline in the documentation and schema design, but don't bother restricting the length and just expand the top bar with the text (then user can decide if too much text looks bad). 
3) Still a little torn on this one, but I think there should be an  `ImageType` like `TextType` and slots can have that type. So for a project, we'd have a`logos` slot with a list of logos of`ImageType`. 
4) We went with `projectDescription` and `resultsOverview` which will handle  `textType` and thus markdown. 
5) Need to discuss filters. Could store a `filter` which contains`filterName` (which can be anything), `filterOptions` within that (which should be a controlled vocabulary within the project - but the project is responsible for making sure the keywords are properly assigned to datasets) and then something like `queryFields` which is a list of solr query-able fields in which to search for these keywords.

**Comment by smfreund** [comment]
I have the same opinion on points 1 and 2 above.

**Comment by emilyodean** [comment]
At our meeting on 3/26 we decided the following -

1) Add `acknoweldgements` as a `textType`
2) Don't  bother enforcing excess restriction/max length for `synopsis` (can do this on frontend if we want)
3) Create `ImageType` with the elements `attribution`,  `licensed`, `caption`, `format`,  `url`, `imageBytes`
We decided we did not want to re-use `distribution` here for the url, but we will use the new `licensed` eml `complexType` here.
4) Went with above suggestions (`projectDescription`, `resultsOverview`)

Todo
- [ ] Look into standards for HTML5 ARIA for accessibility
- [ ] Conversation about filters and how to store them

Working repo continues to be my fork 
 on the 2_2 branch - https://github.com/emilyodean/eml/tree/BRANCH_EML_2_2

**Comment by emilyodean** [comment]
Project and collection serialization is captured in [this folder](https://github.com/NCEAS/project-papers/tree/master/project-schema).

`metacatui-project.xsd` contains project schema and `metacatui-project.xml` is a working example project document.

`metacatui-collection.json` contains the collection/filter schema and `exmplecollection.json` is a working example of a collection. `metacatui-collection-definitions.json` contains definitions for all json attributes. 

[Working SASAP project document here.](https://github.com/NCEAS/project-papers/blob/master/ProjectPageXML2.xml)

**Comment by laurenwalker** [comment]
I've reopened this issue since we are still gradually working on updating this document.

I just made a change to the filters that define the SASAP collection that I think would be helpful for @robyngit to look at since she'll be creating the DBO document as well.

Commit: https://github.com/NCEAS/project-papers/commit/ac96a6b981b6264e930aab617b5d89a4b889ab84

I removed the "-obsoletedBy:*" filter since this will get included automatically by the DataCatalogView. (By default, we search for metadata objects that are not obsoleted.)

I also changed the apostrophe character in the SASAP filter since it looks like all the EML documents use the Unicode character `U+2019` rather than `U+0027`.

I also changed the field name to `project` instead of `projectText`.

**Comment by jeanetteclark** [comment]
pid for this document is `urn:uuid:a03fae16-1ebe-4663-b369-c5f691ae2cb2`, will obsolete this pid when the document is updated, and @csjx will assign a seriesID

**Comment by robyngit** [comment]
updated with pid `urn:uuid:3f1e5802-661b-4889-a97a-24bd85fa4321`. The seriesID (`sid`) is `urn:uuid:db68e045-fe37-4190-aa2f-d79fd854df6d`

**Comment by jeanetteclark** [comment]
updated project document with the version from my latest commit - new pid is `urn:uuid:89dd0291-918a-49e7-8c30-51e30949411f`, sid is the same

**Comment by laurenwalker** [comment]
Let's update the SASAP logo so it's not so pixelated and doesn't have a border.
<img width="546" alt="screen shot 2019-01-11 at 2 13 00 pm" src="https://user-images.githubusercontent.com/6643222/51054497-050f7200-15ab-11e9-81b2-d36f53930d48.png">

**Comment by laurenwalker** [comment]
Also, we should copy over all the SASAP datasets from the KNB to dev.nceas to we can test the SASAP project filters

**Comment by jkibele** [comment]
I tried to update the project document with a new one (541d6ffb8ef5edcfb28de1931fc3c072825f2276) on the dev knb, but I think my user does not have permission to update the document. I got this: 

```
Updating object autogen.2019020112483505360 with the file at ../project-papers/docs/examples/metacatui-project-sasap.xml.
Error in .local(x, ...) : 
  Error updating autogen.2019020112483505360: The provided identity does not have permission to UPDATE the object identified by autogen.2019020112483505360 on the Member Node.
```

I tried to bug @jeanetteclark about it on slack, but it was too late in the day. I'll bother someone about it on Monday.

**Comment by laurenwalker** [comment]
I think @jeanetteclark or @csjx will need to add you to the knb-data-admins group. They are the owners of that group. (If either of you could add me as a owner too, that'd be helpful)

**Comment by jkibele** [comment]
Someone got me the permissions. ...and I've already forgotten who it was. ...but thank you person!
